export enum ErrorCode {
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',

  INVALID_SESSION = 'INVALID_SESSION',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FOOT_NOT_FOUND = 'FOOD_NOT_FOUND',

  AI_PARSE_FAILED = 'AI_PARSE_FAILED',
}
